// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FirstTrap: typeof import('./src/components/FirstTrap.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondTrap: typeof import('./src/components/SecondTrap.vue')['default']
    Seeker: typeof import('./src/components/Seeker.vue')['default']
  }
}
