// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FirstTrap: typeof import('./components/FirstTrap.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondTrap: typeof import('./components/SecondTrap.vue')['default']
    Seeker: typeof import('./components/Seeker.vue')['default']
    Tree: typeof import('./components/InjectTree/Tree.vue')['default']
    UseInjectTree: typeof import("./components/InjectTree/useInjectTree.ts")["default"]
  }
}
